[package]
name = "httpencode"
version = "0.1.0"
authors = ["Sean Lynch <slynch@twitter.com>"]
edition = "2018"

[features]
std = [ ]
default = [ "std" ]

[dependencies]
# httparse = "1.3"
bytes = "0.4"
memchr = "2.2"
